#include "../Include/PCH.h"
#include "Monster_State.h"

IMPLEMENT_SINGLETON(MONSTER_IDLE)
IMPLEMENT_SINGLETON(MONSTER_ATTACK)
IMPLEMENT_SINGLETON(MONSTER_CHASE)
IMPLEMENT_SINGLETON(MONSTER_DAMAGED)
IMPLEMENT_SINGLETON(MONSTER_DEAD)

VOID MONSTER_IDLE::FSM_StateEnter()		{}
VOID MONSTER_IDLE::FSM_StateUpdate()	{}
VOID MONSTER_IDLE::FSM_StateExit()		{}

VOID MONSTER_ATTACK::FSM_StateEnter()	{}
VOID MONSTER_ATTACK::FSM_StateUpdate()	{}
VOID MONSTER_ATTACK::FSM_StateExit()	{}

VOID MONSTER_CHASE::FSM_StateEnter()	{}
VOID MONSTER_CHASE::FSM_StateUpdate()	{}
VOID MONSTER_CHASE::FSM_StateExit()		{}

VOID MONSTER_DAMAGED::FSM_StateEnter()	{}
VOID MONSTER_DAMAGED::FSM_StateUpdate()	{}
VOID MONSTER_DAMAGED::FSM_StateExit()	{}

VOID MONSTER_DEAD::FSM_StateEnter()		{}
VOID MONSTER_DEAD::FSM_StateUpdate()	{}
VOID MONSTER_DEAD::FSM_StateExit()		{}