#pragma once

enum class PLAYER_SKILL		{ SKILL_1, SKILL_2, SKILL_3, SKILL_END, FAIRY_PULSE, ICEARROW_PULSE, EVILHEAD_PULSE, WIND_PULSE, WIND_CHARGING, FAIRY_HITEFFECT,WIND_HITEFFECT
							, ICE_CHARGING, ICE_CHARGE, ICE_SHADER};

enum class MONSTER_EFFECT	{ SKILL_1, SKILL_2, SKILL_3, SKILL_END };

enum class MAIN_UI_EFFECT	{ HP_EFFECT, COIN_EFFECT, DASHSTOCK_EFFECT, TOKEN_EFFECT};

enum class NPC_CHARACTER	{ NPC_TIF, NPC_SHOP, NPC_END };