#pragma once

enum class PLAYER_SKILL		{ SKILL_1, SKILL_2, SKILL_3, SKILL_END };

enum class MONSTER_SKILL	{ SKILL_1, SKILL_2, SKILL_3, SKILL_END };

enum class MAIN_UI_EFFECT	{ HP_EFFECT, COIN_EFFECT, DASHSTOCK_EFFECT, TOKEN_EFFECT};