#pragma once

enum class PLAYER_SKILL {
	SKILL_1, SKILL_2, SKILL_3, SKILL_END, FAIRY_PULSE, ICEARROW_PULSE, EVILHEAD_PULSE, WIND_PULSE, WIND_CHARGING, FAIRY_HITEFFECT, WIND_HITEFFECT,
	FAIRY_CHARGE, FAIRY_CHARGING, ICE_CHARGING, ICE_CHARGE, ICE_SHADER, ICE_HITEFFECT, ICE_THORN, EVIL_HITEFFECT, EVIL_WAVE_EFFECT,
	EVIL_THUNDER, EVIL_CHARGING, EVIL_CHARGE, ARROW_HITEFFECT, WIND_AURA, NPC_TIMESLOW, NPC_TIMESLOW_LOOP, SHADOW, BLUE_SHADER
	, NPC_AREA, ICE_BOMB, WIND_SPIRIT, WIND_WINDY, GREEN_SHADER, WIND_PULSE2, SHADOW_PARTNER, PAREND, CHAOS_PULSE, SKILL2_HAND
	, ANERGYPAR, BLACKHOLE_DEATH, IRA_HITEFFECT, IRA_CHARGING, IRA_CHARGED, ATOMIC_BOW, NPC_ATOMIC, ATOMIC_READY, ATOMIC_BOMB_EFFECT
	, NPC_ATOMIC_CHARGED, NPC_ATOMIC_CHARGED_END, NPC_ATOMIC_AREA};

enum class BOSS_EFFECT		{ 
	SPOOL_APPEAR_EFFECT, SPOOL_FLOW_EFFECT, SPOOL_DISAPPEAR_EFFECT, EMBLEM_APPEAR_EFFECT, EMBLEM_DESTROY_EFFECT, WATER_POPUP_EFFECT, FLAME_EFFECT, CIRCLE_FLAME_EFFECT, SPIRAL_FLAME_EFFECT,
	RSWING_EFFECT, FSWING_CHARGE_EFFECT, FSWING_CHARGE_ELECTRIC_EFFECT, FSWING_ELECTRIC_EFFECT, FSWING_CIRCLE_EFFET, FSWING_EXP_EFFECT,
	SLAM_CIRCLE_EFFET, SLAM_ELECTRIC_EFFECT, SLAM_WARNING_EFFECT, SLAM_GROUND_EXP_EFFECT, 
	METEOR_SLAM_FLAME_EFFECT, METEOR_EFFECT, METEOR_EXP_EFFECT, DANGER_AREA_EFFECT, FIREBALL_EFFECT, SUPPORTER_EFFECT, SUPPORTER_APPEAR_EFFECT, SUPPORTER_STAY_EFFECT, SUPPORTER_DISAPPEAR_EFFECT,
	
	RAGE_CHARGE_ELECTRIC_EFFECT, RAGE_CHARGE_ROAR_EFFECT, 
	RAGE_RSWING_EFFECT, RAGE_FIREBALL_EFFECT, RAGE_SLAM_GROUND_EXP_EFFECT, RAGE_SLAM_CIRCLE_EFFET, RAGE_SLAM_FLAME_EFFECT, EFFECT_END};

enum class MONSTER_EFFECT	{ MONSTER_SUMMONS01, MONSTER_SUMMONS02, MONSTER_SUMMONS03, MONSTER_DEATH, 
							BULLET_STANDARD_BIRTH, BULLET_STANDARD_BIRTHRAY, BULLET_STANDARD_CHARGE,	BULLET_STANDARD_DEATH,
							ALERT_CIRCLE, 
							SKILL_END };

enum class MAIN_UI_EFFECT	{ HP_EFFECT, COIN_EFFECT, DASHSTOCK_EFFECT, TOKEN_EFFECT, AUGMENT_EFFECT};

enum class NPC_CHARACTER	{ NPC_TIF, NPC_SHOP, NPC_END };

enum class ITEM_TYPE		{ NORMAL_WEAPON, NORMAL_UTILITY, RARE_WEAPON, RARE_UTILITY, SUPPLY };

enum class BOSSMODE			{ MODE_INVALIDATE, MODE_RAGE, MODE_ACTION_AVAILABLE, MODE_DEATH, MODE_END };